module.exports = new require('mongoose').Schema({
  blockindex: {type: Number, default: 0, index: true},
  nethash: { type: Number, default: 0 },
  nethash_ghostrider: { type: Number, default: 0 },
  nethash_yespower: { type: Number, default: 0 },
  nethash_lyra2: { type: Number, default: 0 },
  nethash_sha256d: { type: Number, default: 0 },
  nethash_scrypt: { type: Number, default: 0 },
  nethash_memehash: { type: Number, default: 0 },
  nethash_mike: { type: Number, default: 0 },
  difficulty_pow: { type: Number, default: 0 },
  difficulty_pos: { type: Number, default: 0 },
  difficulty_ghostrider: { type: Number, default: 0 },
  difficulty_yespower: { type: Number, default: 0 },
  difficulty_lyra2: { type: Number, default: 0 },
  difficulty_sha256d: { type: Number, default: 0 },
  difficulty_scrypt: { type: Number, default: 0 },
  difficulty_memehash: { type: Number, default: 0 },
  difficulty_mike: { type: Number, default: 0 }
}, {id: false})