module.exports = new require('mongoose').Schema({
  coin: { type: String, required : true },
  genesishash: { type: String, default: '' },
  starttime: { type: Number, default: -1 },
  chain: { type: String, required : true },
  count: { type: Number, default: 1 }, // headers
  last: { type: Number, default: 1 }, // blocks
  supply: { type: Number, default: 0 },
  addresses: { type: Number, default: 0 },
  count_txes: { type: Number, default: 0 },
  count_utxos: { type: Number, default: 0 },
  bestblockhash: { type: String, lowercase: true, default: 'n/a'},
  pow_algo_id: { type: Number },
  pow_algo: { type: String },
  connections: { type: Number, default: 0 },
  smartnodes_total: { type: Number, default: 0 },
  smartnodes_enabled: { type: Number, default: 0 },
  last_price: { type: Number, default: 0 },
  last_usd_price: { type: Number, default: 0 },
  blockchain_last_updated: { type: Number, default: 0 },
  reward_last_updated: { type: Number, default: 0 },
  masternodes_last_updated: { type: Number, default: 0 },
  network_last_updated: { type: Number, default: 0 },
  richlist_last_updated: { type: Number, default: 0 },
  markets_last_updated: { type: Number, default: 0 },
  nethash: { type: Number, default: 0 },
  nethash_ghostrider: { type: Number, default: 0 },
  nethash_yespower: { type: Number, default: 0 },
  nethash_lyra2: { type: Number, default: 0 },
  nethash_sha256d: { type: Number, default: 0 },
  nethash_scrypt: { type: Number, default: 0 },
  difficulty: { type: Number, default: 0 },
  difficulty_pow: { type: Number, default: 0 },
  difficulty_pos: { type: Number, default: 0 },
  difficulty_ghostrider: { type: Number, default: 0 },
  difficulty_yespower: { type: Number, default: 0 },
  difficulty_lyra2: { type: Number, default: 0 },
  difficulty_sha256d: { type: Number, default: 0 },
  difficulty_scrypt: { type: Number, default: 0 },
  mediantime: { type: Number, required: false },
  initialblockdownload: { type: Boolean },
  verificationprogress: { type: Number },
  chainwork: { type: String, lowercase: true, default: 'n/a' },
  size_on_disk: { type: Number, required : false },
  pruned: { type: Boolean, required : false },
})